from __future__ import annotations

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Integer,
    MetaData,
    String,
    Table,
    Text,
)

metadata = MetaData()

inventory_sources = Table(
    "inventory_sources",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("scope_key", String(255), nullable=False),
    Column("openstack_project_id", String(255)),
    Column("openstack_project_name", String(255)),
    Column("region_name", String(255)),
    Column("auth_url", Text),
    Column("is_active", Boolean, nullable=False),
    Column("last_successful_sync_at", DateTime(timezone=True)),
    Column("last_failed_sync_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)

projects = Table(
    "projects",
    metadata,
    Column("inventory_source_id", BigInteger, primary_key=True),
    Column("id", String(255), primary_key=True),
    Column("region_name", String(255)),
    Column("name", String(255)),
    Column("project_id", String(255)),
    Column("status", String(255)),
    Column("description", Text),
    Column("is_enabled", Boolean),
    Column("domain_id", String(255)),
    Column("raw", JSON),
    Column("first_seen_at", DateTime(timezone=True)),
    Column("last_seen_at", DateTime(timezone=True)),
    Column("resource_created_at", DateTime(timezone=True)),
    Column("resource_updated_at", DateTime(timezone=True)),
    Column("is_deleted", Boolean, nullable=False),
    Column("deleted_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)

servers = Table(
    "servers",
    metadata,
    Column("inventory_source_id", BigInteger, primary_key=True),
    Column("id", String(255), primary_key=True),
    Column("region_name", String(255)),
    Column("name", String(255)),
    Column("project_id", String(255)),
    Column("status", String(255)),
    Column("user_id", String(255)),
    Column("flavor_id", String(255)),
    Column("image_id", String(255)),
    Column("availability_zone", String(255)),
    Column("compute_host", String(255)),
    Column("vm_state", String(255)),
    Column("power_state", String(255)),
    Column("addresses", JSON),
    Column("metadata_json", JSON),
    Column("launched_at", DateTime(timezone=True)),
    Column("terminated_at", DateTime(timezone=True)),
    Column("first_seen_at", DateTime(timezone=True)),
    Column("last_seen_at", DateTime(timezone=True)),
    Column("resource_created_at", DateTime(timezone=True)),
    Column("resource_updated_at", DateTime(timezone=True)),
    Column("is_deleted", Boolean, nullable=False),
    Column("deleted_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("raw", JSON),
)

server_tags = Table(
    "server_tags",
    metadata,
    Column("inventory_source_id", BigInteger, primary_key=True),
    Column("server_id", String(255), primary_key=True),
    Column("tag", String(128), primary_key=True),
)

server_addresses = Table(
    "server_addresses",
    metadata,
    Column("inventory_source_id", BigInteger, primary_key=True),
    Column("server_id", String(255), primary_key=True),
    Column("network_name", String(255), primary_key=True),
    Column("address", String(255), primary_key=True),
    Column("address_type", String(64)),
    Column("version", Integer),
    Column("mac_address", String(255)),
    Column("raw", JSON),
)

networks = Table(
    "networks",
    metadata,
    Column("inventory_source_id", BigInteger, primary_key=True),
    Column("id", String(255), primary_key=True),
    Column("region_name", String(255)),
    Column("name", String(255)),
    Column("project_id", String(255)),
    Column("status", String(255)),
    Column("mtu", Integer),
    Column("admin_state_up", Boolean),
    Column("is_shared", Boolean),
    Column("is_router_external", Boolean),
    Column("provider_network_type", String(255)),
    Column("provider_physical_network", String(255)),
    Column("provider_segmentation_id", Integer),
    Column("raw", JSON),
    Column("first_seen_at", DateTime(timezone=True)),
    Column("last_seen_at", DateTime(timezone=True)),
    Column("resource_created_at", DateTime(timezone=True)),
    Column("resource_updated_at", DateTime(timezone=True)),
    Column("is_deleted", Boolean, nullable=False),
    Column("deleted_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)

images = Table(
    "images",
    metadata,
    Column("inventory_source_id", BigInteger, primary_key=True),
    Column("id", String(255), primary_key=True),
    Column("region_name", String(255)),
    Column("name", String(255)),
    Column("project_id", String(255)),
    Column("status", String(255)),
    Column("visibility", String(255)),
    Column("container_format", String(255)),
    Column("disk_format", String(255)),
    Column("min_disk", Integer),
    Column("min_ram", Integer),
    Column("size_bytes", BigInteger),
    Column("checksum", String(255)),
    Column("raw", JSON),
    Column("first_seen_at", DateTime(timezone=True)),
    Column("last_seen_at", DateTime(timezone=True)),
    Column("resource_created_at", DateTime(timezone=True)),
    Column("resource_updated_at", DateTime(timezone=True)),
    Column("is_deleted", Boolean, nullable=False),
    Column("deleted_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)

flavors = Table(
    "flavors",
    metadata,
    Column("inventory_source_id", BigInteger, primary_key=True),
    Column("id", String(255), primary_key=True),
    Column("region_name", String(255)),
    Column("name", String(255)),
    Column("project_id", String(255)),
    Column("status", String(255)),
    Column("vcpus", Integer),
    Column("ram_mb", Integer),
    Column("disk_gb", Integer),
    Column("ephemeral_gb", Integer),
    Column("swap_mb", Integer),
    Column("is_public", Boolean),
    Column("raw", JSON),
    Column("first_seen_at", DateTime(timezone=True)),
    Column("last_seen_at", DateTime(timezone=True)),
    Column("resource_created_at", DateTime(timezone=True)),
    Column("resource_updated_at", DateTime(timezone=True)),
    Column("is_deleted", Boolean, nullable=False),
    Column("deleted_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)
